### ISSUE TITLE
Z-index conflict between cute-alert modes and a modal form.

### ISSUE THREAD

**Issue by mchomem** [gustavosmanc/cute-alert#1]
Would you be able to implement a z-index in the dialog box?

**Comment by gustavosmanc** [comment]
Hello, there's already a z-index implemented for both dialog and toast. Did you have any issues while implementing it?

**Comment by gustavosmanc** [comment]
FYI, this lib was created for studies purpose, I intend to update it and add it to npm later on, in a way it also has compatibility with frameworks such as Vue, React, etc. Feel free to push PRs if you find any bugs or have an idea that would contribute with the project.

**Comment by mchomem** [comment]
I had a problem with z-index, is that when using the component it ended up being displayed behind a modal, so I wanted to know if there was already a parameter where I could manipulate the z-index, I looked in the project wiki but I couldn't find any example.

**Comment by gustavosmanc** [comment]
As of the moment there is no parameter for it, but instead, it's already set as default to the maximum value, shouldn't be causing that error with the modal. Maybe the modal library also sets the z-index value to a maximum, so I would try replacing the modal's z-index to a lower value.

**Comment by mchomem** [comment]
Hello, dear, in my situation, if I put Z-index: 999999 in the alert-wrapper style class instead of alert-frame, the problem is solved.
Analyzing the component code, I understood that the div with alert-wrapper is the top container of the component. Do you see any side effects that could harm the component in a situation where there are no other modalities?

If there is no problem, could you update your source code with this solution?

Note: this change is applied when there is another modal in the project.

**Comment by gustavosmanc** [comment]
Sure, will do that, seems like a solid approach to me, thanks for the tip.

**Comment by mchomem** [comment]
Gustavo, we are using cute-alert on the cdn, what time is more or less the update on the cdn?

I thank you in advance for your attention.

**Comment by gustavosmanc** [comment]
As of the moment I don't have a CDN version for this library. I might upload create one in the future but as I mentioned before, it's a project that I created for studies purpose only, and currently I don't have much time to keep it up to date. But every suggestion is welcome, and as long as people (like you) keep bringing suggestions up I will try to keep up and help them the best way I can. Apparently the library got a bigger repercussion than I expected it to have, I'll try to get a weekend to update a few quality of life related stuff, and also release an NPM and CDN version for it.
