### ISSUE TITLE
close button

### ISSUE THREAD

**Issue by chyasif** [gustavosmanc/cute-alert#12]
After showing the Dialog want to close the window using Enter button of the keyboard . Is it possible?

**Comment by gustavosmanc** [comment]
Hey, good morning! It's not something I intend to add (as it's not very common as far as UX is concerned), but you can easily add this functionality by adding an event listener to the close button.

e.g.
``` 
alertClose.addEventListener('keypress', e => {
  if (e.key === 'Enter') {
    alertWrapper.remove();
    resolve();
  }
});
```
