### ISSUE TITLE
When adding this project to an addon for Firefox warnings are generated

### ISSUE THREAD

**Issue by psmits1567** [gustavosmanc/cute-alert#13]
I am using this beautiful library for my project, but now if I present it to Firefox to publish it as an add-on, there are warnings shown
Unsafe call to body.insertAdjacentHTML for argument 1
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.

cute-alert.js 
It would be great if this could be altered so this warning is prevented

**Comment by gustavosmanc** [comment]
Hey @psmits1567, thanks for the feedback. I plan to improve how the pop-ups are generated in the next update, which you can check on [this PR](https://github.com/gustavosmanc/cute-alert/pull/30). I'll take this feedback into account and come up with a fix for it.
