### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by demoran23** [gustavosmanc/cute-alert#19]
I started to use this project by importing it as an npm git dependency, but I found that the internals of the alerts actually interrogated the scripts and tried to pluck the svgs off of that, so I decided it wasn't worth the hassle to rewrite it to use base64 versions (since I'm bundling this).

Anyway, I did make a typescript definition file for the project, and I wanted to share it with you.  Here's the definitions:

``` typescript
declare module 'cute-alert/cute-alert' {
  export declare type AlertType =
    | 'warning'
    | 'error'
    | 'success'
    | 'question'
    | 'info';

  export declare interface AlertArgs {
    type: AlertType;
    title: string;
    message: string;
    img: string;
    buttonText?: string;
    confirmText?: string;
    vibrate?: number | number[];
    playSound?: string;
    cancelText?: string;
    closeStyle: string;
  }

  export declare interface ToastArgs {
    type: AlertType;
    message: string;
    timer?: number;
    vibrate?: number | number[] | undefined;
    playSound?: string;
  }

  export function cuteAlert(
    args: AlertArgs,
  ): Promise<'confirm' | 'ok' | 'close' | void>;
  export function cuteToast(args: ToastArgs): Promise<void>;
}
```

**Comment by gustavosmanc** [comment]
Hey @demoran23, I appreciate the feedback. I'm working on a refactor [PR](https://github.com/gustavosmanc/cute-alert/pull/30) in which I'm including TypeScript and also other features / improvements. Having that said I'll be closing this issue.
