### ISSUE TITLE
Image in alert is undefined, returns 404 error

### ISSUE THREAD

**Issue by aderowbotham** [gustavosmanc/cute-alert#21]
My folder structure is 
`public/diary-assets/libraries/cute-alert`
with the HTML file + server root being `public`

Using cuteAlert of the box no image shows:

<img width="331" alt="Screenshot 2022-05-07 at 18 30 16" src="https://user-images.githubusercontent.com/85855/167265313-38ad4025-adbc-4b58-a9ab-15e271608f73.png">

The path it is trying to load from is:
`/diary-assets/libraries/cute-alert/undefined`

The problem seems to be line 65:

`${img !== '' ? '<img class="alert-img" src="' + src + '/' + img + '" />' : ''}`

`img` is **undefined** which does not strictly equal `''`

Changing line 65 to the following appears to fix the issue:

`${img !== '' ? '<img class="alert-img" src="' + src + '/img/' + type + '.svg" />' : ''}`

It sees that surely the img filename must be made using the property `type` and the existing code does not appear to do this.

However I don't understand the original intention of checking if `img != ''`, so maybe my fix breaks some other functionality I am not aware of.

**Comment by Xworld777** [comment]
Thank you

**Comment by YassineBaghdadi** [comment]
> My folder structure is `public/diary-assets/libraries/cute-alert` with the HTML file + server root being `public`
> 
> Using cuteAlert of the box no image shows:
> 
> <img alt="Screenshot 2022-05-07 at 18 30 16" width="331" src="https://user-images.githubusercontent.com/85855/167265313-38ad4025-adbc-4b58-a9ab-15e271608f73.png">
> 
> The path it is trying to load from is: `/diary-assets/libraries/cute-alert/undefined`
> 
> The problem seems to be line 65:
> 
> `${img !== '' ? '<img class="alert-img" src="' + src + '/' + img + '" />' : ''}`
> 
> `img` is **undefined** which does not strictly equal `''`
> 
> Changing line 65 to the following appears to fix the issue:
> 
> `${img !== '' ? '<img class="alert-img" src="' + src + '/img/' + type + '.svg" />' : ''}`
> 
> It sees that surely the img filename must be made using the property `type` and the existing code does not appear to do this.
> 
> However I don't understand the original intention of checking if `img != ''`, so maybe my fix breaks some other functionality I am not aware of.

thanks it eorked for me

**Comment by odutra-dev** [comment]
The project was structured in this way so that the developer could choose the desired image, instead of using the images from the repository. But glad it worked in your case.

**Comment by aderowbotham** [comment]
I see. That design intention – i.e. "supply your own image" was not obvious to me.

Helpfully including one image per `type` seems to imply that those should be displayed automatically and by default *unless* perhaps overridden by the developer. But in fact you either supply `img` or no image us shown (due to the else case `: '' }` )

**Comment by odutra-dev** [comment]
Yes, but this change was made to give that freedom to the developer. But it is easily modified to use type.

`<img src="src + / img.svg" />+`

If I'm not wrong. :D

**Comment by aderowbotham** [comment]
I will try it out. To be clear it’s not a criticism, just confusion about
how it was intended to be used with the default images. Thank you!
-- 
mobile: 07754162910
skype: aderowbotham
aderowbotham.com

**Comment by odutra-dev** [comment]
This one! We are here to collaborate with the community!

In case you're interested, I used this library as a base to write mine. If you want to use it and make a pull request with any changes or suggestions, feel free!

https://github.com/DutraGames/awesome-alert
