### ISSUE TITLE
Toast bar ios and macos

### ISSUE THREAD

**Issue by RaisTMJ** [gustavosmanc/cute-alert#23]

**Comment by RaisTMJ** [comment]
Toastbar ios and macos not able to close down or automatically close when using apple device.

**Comment by gustavosmanc** [comment]
Hey @RaisTMJ, I appreciate the feedback. I'm working on a [PR](https://github.com/gustavosmanc/cute-alert/pull/30) in which I plan to improve how the pop-ups are generated for the library, alongside other improvements and features. I'll take this feedback into account and come up with a fix for it.
