### ISSUE TITLE
Add option for close Alert with timer

### ISSUE THREAD

**Issue by ChemaBautista** [gustavosmanc/cute-alert#24]
Add option for close Alert with timer
`function cuteAlertAction(type, title, message){
  return cuteAlert({
    type: type,
    title: title,
    message: message,
    autoClose: true,
    timer: 2000
  });
}`

**Comment by gustavosmanc** [comment]
Hey @ChemaBautista, thanks for the feedback. I'm working on a refactor [PR](https://github.com/gustavosmanc/cute-alert/pull/30) in which I'm including this feature and also other improvements overall. Having that said I'll be closing this issue.
