### ISSUE TITLE
cute-alert confirmation with promises??

### ISSUE THREAD

**Issue by 831220** [gustavosmanc/cute-alert#3]
When I use cute alert for delete or any other actions confirmation, action happens anyway because promise don't block it. So it deletes the item even if I click on Cancel. 
How to avoid this? 
Note: Thanks a lot for this beautiful and easy to use library!!

**Comment by gustavosmanc** [comment]
Thank you for the feedback 😄 . Can you send me an example of how are you implementing it? Just so I can narrow down the issue.

**Comment by 831220** [comment]
_Sure... This is my form..._ 


```
<form action="{{route('admin.agencies.destroy', $id)}}" method="POST">
    @csrf
    @method('delete')

    <a class="btn btn-warning btn-sm" href="{{route('admin.agencies.edit', $id)}}"
       data-toggle="tooltip" data-placement="top" title="Editar la agencia"><i class="fas fa-pencil-alt"></i></a>

    <button type="submit" class="btn btn-warning btn-sm" data-toggle="tooltip" id="delete"
            onclick="return confirmate('¿Realmente desea realizar esta acción?') === true; " data-placement="top" title="Eliminar la agencia"><i class='fas fa-trash-alt'></i></button>
</form>
```


_Then the function that uses cute-alert:_

```

<script>
function confirmate(text) {
   return cuteAlert({
        type: "question",
        title: "Confirmación",
        message: text.toString(),
        confirmText: "Confirmar",
        cancelText: "Cancelar"
    }).then((e)=>{
        if ( e == ("confirm")){
            return true;
        } else {
            return false;
        }
    })
}
</script>
```


Obviously the submit does not awaits for the .then() to execute, so... how do I use cute-alert confirmation to do that kind of tasks... This looks more like stackoverflow question, I'm sorry.

**Comment by gustavosmanc** [comment]
yeah, in this case what you could try to do is refactor it into:
```
<script>
async function confirmate(text) {
  const e = await cuteAlert({
    type: 'question',
    title: 'Confirmación',
    message: text.toString(),
    confirmText: 'Confirmar',
    cancelText: 'Cancelar',
  });

  if (e === 'confirm') {
    return true;
  }

  return false;
}
</script>
```

**Comment by 831220** [comment]
Thanks!!!
Somehow if I use that code this way:

```
<button type="submit" class="btn btn-warning btn-sm" data-toggle="tooltip" id="delete"
            onclick="return true === confirmate('¿Realmente desea realizar esta acción?'); " data-placement="top" title="Eliminar"><i class='fas fa-trash-alt'></i></button>
```
Nothing happens at clicking the confirmation, but I do:

```
<button type="submit" class="btn btn-warning btn-sm" data-toggle="tooltip" id="delete"
            onclick="return confirmate('¿Realmente desea realizar esta acción?'); " data-placement="top" title="Eliminar la agencia"><i class='fas fa-trash-alt'></i></button>
```

Then again it deletes without waiting for confirmation at all. I guess someting is wrong... because I alerted the function and says true... so I am doing it wrong somehow. Toasts work great by the way...

**Comment by gustavosmanc** [comment]
You don't need that return before calling confirmate, since the function already returns you something.

**Comment by gustavosmanc** [comment]
I might be wrong, but as you are using @method('delete') from Laravel, it might be triggering the delete method from the controller by default (just because submit is being thrown). Therefore, what you really want to do, is get the return from confirmate inside that method (in the controller) and handle deletion / not deletion from there.

**Comment by 831220** [comment]
Actually, when condition is false, it does not deletes nothing. Problem is that primitive boolean is not the same that Promise(boolean). 
Can this confirmation have a variant without promise? Is it dificult to provide such version. I would like to use your code in all our platform... not only using the toast to notify but the ugly primitive confirm() window for the confirmations... If its too much trouble, nevermind... thanks a lot.

**Comment by gustavosmanc** [comment]
It's more of a Laravel issue, not the alert lib itself. As you are doing a request from an endpoint, the best way would be for you to use ajax to do that request. Unfortunately, there is no other way to return that confirmation without a promise.

**Comment by 831220** [comment]
> It's more of a Laravel issue, not the alert lib itself. As you are doing a request from an endpoint, the best way would be for you to use ajax to do that request. Unfortunately, there is no other way to return that confirmation without a promise. Have you tried doing an ajax request inside confirmate instead of using @method('delete')? I can help you with that if you don't know how to.

That would be great! So I can use your lib in all the system. How do I change the laravel form into an ajax request that waits for the promise of the cute-alert confirmation?
