### ISSUE TITLE
new instances duplicate on page

### ISSUE THREAD

**Issue by JacquesOkes** [gustavosmanc/cute-alert#6]
This really is great, thanks first of all!
Second, If I confirm box, and choose cancel, then go into it again, it duplicates the confirmation box.
It's as if the first never disposes properly. So I have one confirmation box to close, then I have to close it again - you can also see the background gets darker each time you load a new one.

Do you have a dispose event I could use to ensure each new call is only done so once?

**Comment by JacquesOkes** [comment]
It actually happens when I have a success box, then after that have a confirm box, then it seems to duplicate on the confirm...

**Comment by gustavosmanc** [comment]
Hey, thank you for the feedback! Can you upload a video demonstrating the issue?

**Comment by JacquesOkes** [comment]
https://user-images.githubusercontent.com/42800527/126755127-a531f5f1-9b0e-4fa3-9427-dc7a696b3a33.mp4

Here we go, video demonstrating the issue.
It could be due to the partial pages ving rendered in a modal, but all the code for each js call to create the alerts is on the layout page, code and calls.

I have managed to fix it with the following code before my call.

```
 try {
            var alertWrapper = document.querySelector(".alert-wrapper");
            alertWrapper.remove();
        } catch (ex) {
            console.log('duplicate not found');
        }
```

This fires the log "duplicate not found" each time, but it does ensure that only 1 content is added via the javascript.

So not really sure if this helps you or anyone else who experienced it, but just letting you know.

Thanks!

**Comment by gustavosmanc** [comment]
How are you making the call to the cuteAlert function? What I could try to do is to implement a similar solution as you did for your code.

**Comment by psmits1567** [comment]
Hi, I added the js as indicated into the manifest. And then call the alert as described in the documentation. So the page itself has no <script> tags

**Comment by gustavosmanc** [comment]
Hey, I added a duplicate handler on the last update. Closing this issue for now, if for some reason it happens again, feel free to open another issue. Thanks for the feedback guys.
