### ISSUE TITLE
If the library is included into an addon with manifest, then the svg images are not shown

### ISSUE THREAD

**Issue by psmits1567** [gustavosmanc/cute-alert#7]
I have added the library to an add-on I am working on. It does not show the "svg" images included on Chrome and other browsers
You have to add the following lines into the manifest

"web_accessible_resources": [
    "/img/*"
  ],

**Comment by gustavosmanc** [comment]
As of the moment the library is not fully supported for manifest, but I intend to turn those svg images into pure css in the future, which should fix that issue.
