### ISSUE TITLE
If you have included the library into an add-on, then the cute-alert.js is not recognised

### ISSUE THREAD

**Issue by psmits1567** [gustavosmanc/cute-alert#8]
I have added the library into an add-on without adding the cute-alert.js added into the pages.
That is not necessary if you use a manifest.
To make it work, I altered the following lines in the manifest
 // 13-08-2021 Modified the code below to be able to use it in manifest
        let src = chrome.extension.getURL('/');
        for (let script of scripts) {
          if (script.src.includes("cute-alert.js")) {
              currScript = script;
              src = currScript.src;
              src = src.substring(0, src.lastIndexOf("/"));
            }
        }
This does work for me, but might not work for others, so needs to be tested in a page without using a manifest

**Comment by gustavosmanc** [comment]
As I mentioned in another issue of yours, right now the library is not fully supported for manifest, but thanks for the feedback. Glad to know it works that way.
