### ISSUE TITLE
If the body does not have a parent, then the instruction insertAdjacentHTML('afterend' does not work

### ISSUE THREAD

**Issue by psmits1567** [gustavosmanc/cute-alert#9]
If you have a blanc page that only contains a body, then the instruction does not work.
It could be solved by adding a parameter, that contains a location by ID
In that case if you have a container, you can reference the container, and then it does work again

**Comment by gustavosmanc** [comment]
Hey, thanks for the feedback. Can you send me an example? I tested with a html that contains only a body and wasn't able to reproduce the issue.

**Comment by psmits1567** [comment]
Hi this is the way it works for me now
cuteAlert({
			type: "question",
			title: "Create a back-up for check afterwards",
			message: "To proceed it is necessary to create a back-up!",
			confirmText: "Yes proceed",
			cancelText: "No stop",
			closeStyle: "",
			myWindow : myWindow,
		}).then((e) => {

			if (e == "confirm") {
				cuteToast({
					type: "info",
					message: "Please wait while data is fetched",
					timer: 5000,
					myWindow,
				});

The page is opened as follows
function scrapeconsistency(locale) {
	var currentLocation = window.location;
	var wind;
	wind = "myWindow";
	
	// 09-08-2021 PSS fixed problem with not opening new windows in Chrome issue #114
	var consistsWindow = window.open("https://translate.wordpress.org/consistency/?search=&set=" + locale + "%2Fdefault","https://translate.wordpress.org/consistency/?search=&set=" + locale + "%2Fdefault");
	var myWindow = window.open("", "_blanc");
	var meta = document.createElement('meta');
	meta.setAttribute('name', 'viewport');
	meta.setAttribute('content', 'width=device-width, initial-scale=1.0');
	meta.setAttribute('Content-Type', 'image/svg+xml');
	myWindow.document.getElementsByTagName('head')[0].appendChild(meta);

**Comment by gustavosmanc** [comment]
I suppose that piece of code if from that other issue of yours. In this particular one, you mentioned that the lib doesn't work when opening from a page that contains only a body. Can you provide me an example?

**Comment by psmits1567** [comment]
Ok let me describe how I encountered this problem. The addon is used on translate.wordpress.org. That is a translation platform for wordpress. I created a function to find and replace wrong verbs in the translation database, by invoking the function with a shortkey. That opens a blanc window, which is populated with some fields. If an error occurs then I show your alert. In the beginning without my modification this new screen did not show the alerts on this new window, but instead on the previous window behind it. And also produced the error described.

**Comment by gustavosmanc** [comment]
Hey @psmits1567. As I mentioned in the other issues you've opened, I'm working on a [PR](https://github.com/gustavosmanc/cute-alert/pull/30) in which I plan to improve how the pop-ups are generated for the library.

Thanks for the feedback, I'll take it into account and it should be fixed in the next update.
